// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVKlZTX7OBtdJwPQwznIxVhwLr2WfUoYM',
    appId: '1:1002847016554:web:945cce2e95eeea4089dc13',
    messagingSenderId: '1002847016554',
    projectId: 'nutrical-8c6c1',
    authDomain: 'nutrical-8c6c1.firebaseapp.com',
    storageBucket: 'nutrical-8c6c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqdKbGwSLc84HalxHNCsCcOz39Gi-5NE',
    appId: '1:1002847016554:android:ddb6d9b006772d6c89dc13',
    messagingSenderId: '1002847016554',
    projectId: 'nutrical-8c6c1',
    storageBucket: 'nutrical-8c6c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBet8mFeBK3LfOlQPcFyuZtHeF8j6TseFk',
    appId: '1:1002847016554:ios:258b74003a325ab589dc13',
    messagingSenderId: '1002847016554',
    projectId: 'nutrical-8c6c1',
    storageBucket: 'nutrical-8c6c1.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBet8mFeBK3LfOlQPcFyuZtHeF8j6TseFk',
    appId: '1:1002847016554:ios:476387f18704af1989dc13',
    messagingSenderId: '1002847016554',
    projectId: 'nutrical-8c6c1',
    storageBucket: 'nutrical-8c6c1.appspot.com',
    iosBundleId: 'com.example.testDrive.RunnerTests',
  );
}
